GET http://localhost:3000


##
GET http://localhost:3000/api/v1/software-engineers


##
GET http://localhost:3000/api/v1/software-engineers/1

## 
POST http://localhost:3000/api/v1/software-engineers
Content-Type: application/json

{
    name:"Carlos",
    techStack:"Java React"
}